/**
 * Generic spec-driven computation engine.
 *
 * A "PaperSpec" describes a paper's methodology as an ordered list of blocks.
 * Each block carries:
 *   - params:    slider definitions {key, sym, label, min, max, step, def}
 *   - computeJs: the body of a JS function (input, params, helpers) => number[]
 *                `input` is the previous block's output array (null for block 0).
 *
 * The engine compiles each block once, runs the full pipeline for a parameter
 * set, and returns per-block output arrays plus summary metrics.
 *
 * computeJs code is either hand-written (sample paper) or generated by the AI
 * from an uploaded paper. It runs in the user's own browser with access only
 * to Math and the helpers object.
 */

function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Fixed seeded gaussian track — shared by baseline and modified runs so every
 *  visible difference is caused by parameter edits, never resampled noise. */
function makeNoise(n, seed = 1337) {
  const rnd = mulberry32(seed);
  const out = new Array(n);
  for (let i = 0; i < n; i++) {
    const u1 = Math.max(rnd(), 1e-12), u2 = rnd();
    out[i] = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  }
  return out;
}

export function buildHelpers(protocol) {
  const dt = protocol.dt;
  const n = Math.round(protocol.T / dt) + 1;
  const t = new Array(n);
  for (let i = 0; i < n; i++) t[i] = i * dt;
  return {
    n, dt, t,
    T: protocol.T,
    noise: makeNoise(n),
    clamp: (v, lo, hi) => Math.max(lo, Math.min(hi, v)),
    step: (ti, t0, amp = 1) => (ti >= t0 ? amp : 0),
  };
}

export function defaultsFromSpec(spec) {
  return Object.fromEntries(
    spec.blocks.flatMap((b) => b.params.map((p) => [p.key, p.def]))
  );
}

/** Compile every block's computeJs once. Returns {fns, errors}. */
export function compileSpec(spec) {
  const fns = {};
  const errors = {};
  for (const block of spec.blocks) {
    try {
      // eslint-disable-next-line no-new-func
      fns[block.key] = new Function("input", "params", "helpers", block.computeJs);
    } catch (e) {
      errors[block.key] = `Compile error: ${e.message}`;
    }
  }
  return { fns, errors };
}

/** Run the full pipeline. Returns {outputs: {blockKey: number[]}, error}. */
export function runSpec(spec, compiled, params, helpers) {
  const outputs = {};
  let signal = null;
  for (const block of spec.blocks) {
    const fn = compiled.fns[block.key];
    if (!fn) return { outputs, error: compiled.errors[block.key] || `Block "${block.key}" failed to compile` };
    try {
      signal = fn(signal, params, helpers);
    } catch (e) {
      return { outputs, error: `Runtime error in "${block.title}": ${e.message}` };
    }
    if (!signal || signal.length !== helpers.n) {
      return { outputs, error: `Block "${block.title}" must return an array of length ${helpers.n} (got ${signal ? signal.length : typeof signal})` };
    }
    // sanitize non-finite values so charts never explode
    for (let i = 0; i < signal.length; i++) {
      if (!Number.isFinite(signal[i])) signal[i] = 0;
    }
    outputs[block.key] = signal;
  }
  return { outputs, error: null };
}

/**
 * Compile every panel of every result figure once.
 * Keyed by "figIndex:panelIndex". Returns {fns, errors}.
 */
export function compileResultFigures(spec) {
  const fns = {};
  const errors = {};
  (spec.resultFigures || []).forEach((fig, fi) => {
    (fig.panels || []).forEach((panel, pi) => {
      const id = `${fi}:${pi}`;
      try {
        // eslint-disable-next-line no-new-func
        fns[id] = new Function("outputs", "params", "helpers", panel.computeJs);
      } catch (e) {
        errors[id] = `Compile error: ${e.message}`;
      }
    });
  });
  return { fns, errors };
}

/**
 * Build the helpers object passed to figure-panel kernels. Adds `simulate`,
 * which re-runs the whole methodology pipeline under parameter overrides and
 * returns its output map — this is what lets a figure show comparison curves
 * (with/without control, perturbation sweeps, gain ablations, …) the way the
 * paper's real figures do.
 */
export function makeFigureHelpers(spec, pipelineCompiled, helpers, baseParams) {
  const simulate = (overrides) => {
    const p = overrides ? { ...baseParams, ...overrides } : baseParams;
    const r = runSpec(spec, pipelineCompiled, p, helpers);
    return r.error ? null : r.outputs;
  };
  return { ...helpers, simulate };
}

/**
 * Run one figure panel kernel. Returns { x?, series:[{label,data}], error }.
 * `figHelpers` must be the object from makeFigureHelpers (includes simulate).
 */
export function runResultPanel(fn, outputs, params, figHelpers) {
  if (!fn) return { series: [], error: "panel failed to compile" };
  let res;
  try {
    res = fn(outputs, params, figHelpers);
  } catch (e) {
    return { series: [], error: `Runtime error: ${e.message}` };
  }
  if (!res || !Array.isArray(res.series) || !res.series.length) {
    return { series: [], error: "panel must return { series: [{label, data}] }" };
  }
  const len = res.series[0].data?.length;
  if (!len) return { series: [], error: "panel returned empty series data" };
  for (const s of res.series) {
    if (!Array.isArray(s.data) || s.data.length !== len) {
      return { series: [], error: "all series in a panel must share one length" };
    }
    for (let i = 0; i < s.data.length; i++) {
      if (!Number.isFinite(s.data[i])) s.data[i] = 0;
    }
  }
  let x = res.x;
  if (!Array.isArray(x) || x.length !== len) x = null;
  let categories = res.categories;
  if (!Array.isArray(categories) || categories.length !== len) categories = null;
  return { x, categories, series: res.series, error: null };
}

/** Recharts rows for one panel: baseline (b#) + active (a#) series interleaved. */
export function buildPanelRows(baseRun, actRun) {
  const active = actRun && !actRun.error ? actRun : null;
  const base = baseRun && !baseRun.error ? baseRun : null;
  const ref = active || base;
  if (!ref) return { rows: [] };

  const x = ref.x;
  const n = ref.series[0].data.length;
  const rows = new Array(n);
  for (let i = 0; i < n; i++) {
    const row = { _i: x ? x[i] : i };
    if (active) active.series.forEach((s, k) => { row[`a${k}`] = s.data[i]; });
    if (base)   base.series.forEach((s, k) => { row[`b${k}`] = s.data[i]; });
    rows[i] = row;
  }
  return { rows };
}

/**
 * Validate every panel of every result figure by test-running it.
 * Panels that fail to compile, error at runtime, or plot as flat/constant
 * lines are silently DROPPED — a broken reproduction must never reach the
 * reader. Figures themselves are always kept: the original cropped figure
 * plus its guided-tour explanation is the primary content, with or without
 * interactive panels.
 */
export function validateResultFigures(spec, pipelineCompiled, helpers, baseParams) {
  const figCompiled = compileResultFigures(spec);
  const base = runSpec(spec, pipelineCompiled, baseParams, helpers);
  const figHelpers = makeFigureHelpers(spec, pipelineCompiled, helpers, baseParams);
  return (spec.resultFigures || []).map((fig, fi) => {
    const goodPanels = (fig.panels || []).filter((panel, pi) => {
      const id = `${fi}:${pi}`;
      if (figCompiled.errors[id]) return false;
      const r = runResultPanel(figCompiled.fns[id], base.outputs, baseParams, figHelpers);
      if (r.error) return false;
      // every series flat ⇒ not a real reproduction — drop it
      return r.series.some((s) => signalSpan(s.data) > 1e-9);
    });
    return { ...fig, panels: goodPanels };
  });
}

/** Normalized RMS drift (%) of the final block's output vs baseline. */
export function driftPercent(baseOut, actOut, finalKey) {
  const b = baseOut[finalKey], a = actOut[finalKey];
  if (!b || !a) return 0;
  let num = 0, den = 0;
  for (let i = 0; i < b.length; i++) {
    num += (a[i] - b[i]) ** 2;
    den += b[i] ** 2;
  }
  return 100 * Math.sqrt(num / Math.max(den, 1e-12));
}

/** Generic summary metrics on the final block output. */
export function summaryMetrics(arr) {
  if (!arr || !arr.length) return { peak: 0, rms: 0, mean: 0 };
  let sum = 0, sum2 = 0, peak = -Infinity;
  for (const v of arr) {
    sum += v; sum2 += v * v;
    peak = Math.max(peak, Math.abs(v));
  }
  return {
    peak,
    rms: Math.sqrt(sum2 / arr.length),
    mean: sum / arr.length,
  };
}

/** Merge baseline + active outputs into Recharts rows, keys <blockKey>B / <blockKey>A. */
export function buildRows(spec, helpers, baseOut, actOut) {
  const rows = new Array(helpers.n);
  for (let i = 0; i < helpers.n; i++) {
    const row = { t: +helpers.t[i].toFixed(3) };
    for (const block of spec.blocks) {
      const b = baseOut[block.key], a = actOut[block.key];
      if (b) row[block.key + "B"] = b[i];
      if (a) row[block.key + "A"] = a[i];
    }
    rows[i] = row;
  }
  return rows;
}

/* ---------------- quality audit (anti-garbage validation) ----------------
 * The analyzer's generated code can "run" while modeling nothing — constant
 * arrays plot as flat lines, sliders that aren't wired into the math change
 * nothing, and drift stays 0.0% because baseline and modified are equally
 * dead. These audits test-run the generated code and return a list of
 * human-readable problems; the client feeds them back to the analyzer for
 * one automatic regeneration of the failing phase.
 */

function signalSpan(arr) {
  let lo = Infinity, hi = -Infinity;
  for (const v of arr) { if (v < lo) lo = v; if (v > hi) hi = v; }
  return hi - lo;
}

/** Audit the methodology pipeline: constant block outputs and dead sliders. */
export function auditPipeline(spec, compiled, helpers, defaults) {
  const problems = [];
  if (!spec.blocks?.length) return problems; // no pipeline (by design for this archetype)
  const base = runSpec(spec, compiled, defaults, helpers);
  if (base.error) { problems.push(`the pipeline fails at baseline: ${base.error}`); return problems; }

  for (const b of spec.blocks) {
    const out = base.outputs[b.key];
    if (out && signalSpan(out) < 1e-9) {
      problems.push(`block "${b.key}" (${b.title}) returns a CONSTANT array — it models nothing and plots as a flat line`);
    }
  }

  // Slider responsiveness: nudge every param ~35% toward its max and require
  // the final block's output to change.
  const nudged = { ...defaults };
  for (const b of spec.blocks) {
    for (const p of b.params || []) {
      const target = p.def + (p.max - p.def) * 0.35;
      nudged[p.key] = Number.isFinite(target) && target !== p.def ? target : p.def * 1.35 + 0.01;
    }
  }
  const alt = runSpec(spec, compiled, nudged, helpers);
  if (!alt.error) {
    const fk = spec.blocks[spec.blocks.length - 1].key;
    const a = base.outputs[fk] || [], c = alt.outputs[fk] || [];
    let diff = 0;
    for (let i = 0; i < a.length; i++) diff = Math.max(diff, Math.abs(a[i] - c[i]));
    if (diff / Math.max(1e-9, signalSpan(a)) < 1e-6) {
      problems.push(`moving the sliders does not change the final block "${fk}" output at all — the params are not actually used in the math`);
    }
  }
  return problems;
}

/** Audit reproduced result figures: non-compiling, erroring, or flat panels. */
export function auditResultFiguresQuality(spec, compiled, helpers, defaults) {
  const problems = [];
  const figCompiled = compileResultFigures(spec);
  const base = runSpec(spec, compiled, defaults, helpers);
  if (base.error) return problems; // pipeline problems are reported by auditPipeline
  const fh = makeFigureHelpers(spec, compiled, helpers, defaults);

  (spec.resultFigures || []).forEach((fig, fi) => {
    (fig.panels || []).forEach((panel, pi) => {
      const id = `${fi}:${pi}`;
      const where = `${fig.figureLabel || `figure ${fi + 1}`} panel "${panel.subplotLabel || pi + 1}"`;
      if (figCompiled.errors[id]) { problems.push(`${where} does not compile: ${figCompiled.errors[id]}`); return; }
      const r = runResultPanel(figCompiled.fns[id], base.outputs, defaults, fh);
      if (r.error) { problems.push(`${where} fails at runtime: ${r.error}`); return; }
      const flat = r.series.every((s) => signalSpan(s.data) < 1e-9);
      if (flat) problems.push(`${where} plots as FLAT/CONSTANT lines (every series is constant) — not a real reproduction of the paper's curves`);
    });
  });
  return problems;
}

/** Audit foundation demos: non-compiling, erroring, or flat/empty output. */
export function auditFoundations(spec) {
  const problems = [];
  (spec.foundations || []).forEach((f) => {
    const d = f.demo;
    if (!d) return;
    let fn;
    try {
      // eslint-disable-next-line no-new-func
      fn = new Function("params", "helpers", d.computeJs);
    } catch (e) { problems.push(`foundation "${f.title}" demo does not compile: ${e.message}`); return; }
    const h = buildHelpers({ T: d.T || 1, dt: d.dt || 1 });
    const p = Object.fromEntries((d.params || []).map((pp) => [pp.key, pp.def]));
    let res;
    try { res = fn(p, h); } catch (e) { problems.push(`foundation "${f.title}" demo errors when run: ${e.message}`); return; }
    if (d.kind === "frames") {
      if (!res || !Array.isArray(res.frames) || res.frames.length < 2) {
        problems.push(`foundation "${f.title}" frames demo returns no usable frames`);
      }
    } else {
      const live = res && Array.isArray(res.series) &&
        res.series.some((s) => Array.isArray(s.data) && s.data.length > 3 && signalSpan(s.data.filter(Number.isFinite)) > 1e-9);
      if (!live) problems.push(`foundation "${f.title}" chart demo plots flat or empty — it must show a clearly varying curve that responds to its sliders`);
    }
  });
  return problems;
}
