/**
 * Generic spec-driven computation engine.
 *
 * A "PaperSpec" describes a paper's methodology as an ordered list of blocks.
 * Each block carries:
 *   - params:    slider definitions {key, sym, label, min, max, step, def}
 *   - computeJs: the body of a JS function (input, params, helpers) => number[]
 *                `input` is the previous block's output array (null for block 0).
 *
 * The engine compiles each block once, runs the full pipeline for a parameter
 * set, and returns per-block output arrays plus summary metrics.
 *
 * computeJs code is either hand-written (sample paper) or generated by Claude
 * from an uploaded paper. It runs in the user's own browser with access only
 * to Math and the helpers object.
 */

function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Fixed seeded gaussian track — shared by baseline and modified runs so every
 *  visible difference is caused by parameter edits, never resampled noise. */
function makeNoise(n, seed = 1337) {
  const rnd = mulberry32(seed);
  const out = new Array(n);
  for (let i = 0; i < n; i++) {
    const u1 = Math.max(rnd(), 1e-12), u2 = rnd();
    out[i] = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  }
  return out;
}

export function buildHelpers(protocol) {
  const dt = protocol.dt;
  const n = Math.round(protocol.T / dt) + 1;
  const t = new Array(n);
  for (let i = 0; i < n; i++) t[i] = i * dt;
  return {
    n, dt, t,
    T: protocol.T,
    noise: makeNoise(n),
    clamp: (v, lo, hi) => Math.max(lo, Math.min(hi, v)),
    step: (ti, t0, amp = 1) => (ti >= t0 ? amp : 0),
  };
}

export function defaultsFromSpec(spec) {
  return Object.fromEntries(
    spec.blocks.flatMap((b) => b.params.map((p) => [p.key, p.def]))
  );
}

/** Compile every block's computeJs once. Returns {fns, errors}. */
export function compileSpec(spec) {
  const fns = {};
  const errors = {};
  for (const block of spec.blocks) {
    try {
      // eslint-disable-next-line no-new-func
      fns[block.key] = new Function("input", "params", "helpers", block.computeJs);
    } catch (e) {
      errors[block.key] = `Compile error: ${e.message}`;
    }
  }
  return { fns, errors };
}

/** Run the full pipeline. Returns {outputs: {blockKey: number[]}, error}. */
export function runSpec(spec, compiled, params, helpers) {
  const outputs = {};
  let signal = null;
  for (const block of spec.blocks) {
    const fn = compiled.fns[block.key];
    if (!fn) return { outputs, error: compiled.errors[block.key] || `Block "${block.key}" failed to compile` };
    try {
      signal = fn(signal, params, helpers);
    } catch (e) {
      return { outputs, error: `Runtime error in "${block.title}": ${e.message}` };
    }
    if (!signal || signal.length !== helpers.n) {
      return { outputs, error: `Block "${block.title}" must return an array of length ${helpers.n} (got ${signal ? signal.length : typeof signal})` };
    }
    // sanitize non-finite values so charts never explode
    for (let i = 0; i < signal.length; i++) {
      if (!Number.isFinite(signal[i])) signal[i] = 0;
    }
    outputs[block.key] = signal;
  }
  return { outputs, error: null };
}

/** Normalized RMS drift (%) of the final block's output vs baseline. */
export function driftPercent(baseOut, actOut, finalKey) {
  const b = baseOut[finalKey], a = actOut[finalKey];
  if (!b || !a) return 0;
  let num = 0, den = 0;
  for (let i = 0; i < b.length; i++) {
    num += (a[i] - b[i]) ** 2;
    den += b[i] ** 2;
  }
  return 100 * Math.sqrt(num / Math.max(den, 1e-12));
}

/** Generic summary metrics on the final block output. */
export function summaryMetrics(arr) {
  if (!arr || !arr.length) return { peak: 0, rms: 0, mean: 0 };
  let sum = 0, sum2 = 0, peak = -Infinity;
  for (const v of arr) {
    sum += v; sum2 += v * v;
    peak = Math.max(peak, Math.abs(v));
  }
  return {
    peak,
    rms: Math.sqrt(sum2 / arr.length),
    mean: sum / arr.length,
  };
}

/** Merge baseline + active outputs into Recharts rows, keys <blockKey>B / <blockKey>A. */
export function buildRows(spec, helpers, baseOut, actOut) {
  const rows = new Array(helpers.n);
  for (let i = 0; i < helpers.n; i++) {
    const row = { t: +helpers.t[i].toFixed(3) };
    for (const block of spec.blocks) {
      const b = baseOut[block.key], a = actOut[block.key];
      if (b) row[block.key + "B"] = b[i];
      if (a) row[block.key + "A"] = a[i];
    }
    rows[i] = row;
  }
  return rows;
}
